# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acmecorp/filemanagement/v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from acmecorp.filemanagement.v1 import data_pb2 as acmecorp_dot_filemanagement_dot_v1_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(acmecorp/filemanagement/v1/service.proto\x12\x1a\x61\x63mecorp.filemanagement.v1\x1a%acmecorp/filemanagement/v1/data.proto\"#\n\x0f\x44ownloadRequest\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"H\n\x10\x44ownloadResponse\x12\x34\n\x04\x66ile\x18\x01 \x01(\x0b\x32 .acmecorp.filemanagement.v1.FileR\x04\x66ile2x\n\x0f\x44ownloadService\x12\x65\n\x08\x44ownload\x12+.acmecorp.filemanagement.v1.DownloadRequest\x1a,.acmecorp.filemanagement.v1.DownloadResponseB\xb8\x01\n\x1e\x63om.acmecorp.filemanagement.v1B\x0cServiceProtoP\x01\xa2\x02\x03\x41\x46X\xaa\x02\x1a\x41\x63mecorp.Filemanagement.V1\xca\x02\x1a\x41\x63mecorp\\Filemanagement\\V1\xe2\x02&Acmecorp\\Filemanagement\\V1\\GPBMetadata\xea\x02\x1c\x41\x63mecorp::Filemanagement::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acmecorp.filemanagement.v1.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.acmecorp.filemanagement.v1B\014ServiceProtoP\001\242\002\003AFX\252\002\032Acmecorp.Filemanagement.V1\312\002\032Acmecorp\\Filemanagement\\V1\342\002&Acmecorp\\Filemanagement\\V1\\GPBMetadata\352\002\034Acmecorp::Filemanagement::V1'
  _globals['_DOWNLOADREQUEST']._serialized_start=111
  _globals['_DOWNLOADREQUEST']._serialized_end=146
  _globals['_DOWNLOADRESPONSE']._serialized_start=148
  _globals['_DOWNLOADRESPONSE']._serialized_end=220
  _globals['_DOWNLOADSERVICE']._serialized_start=222
  _globals['_DOWNLOADSERVICE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
