# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acmecorp/filemanagement/v1/data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%acmecorp/filemanagement/v1/data.proto\x12\x1a\x61\x63mecorp.filemanagement.v1\"i\n\x04\x46ile\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04size\x18\x02 \x01(\x04R\x04size\x12\x1b\n\tmime_type\x18\x03 \x01(\tR\x08mimeType\x12\x1c\n\textension\x18\x04 \x01(\tR\textensionB\xb5\x01\n\x1e\x63om.acmecorp.filemanagement.v1B\tDataProtoP\x01\xa2\x02\x03\x41\x46X\xaa\x02\x1a\x41\x63mecorp.Filemanagement.V1\xca\x02\x1a\x41\x63mecorp\\Filemanagement\\V1\xe2\x02&Acmecorp\\Filemanagement\\V1\\GPBMetadata\xea\x02\x1c\x41\x63mecorp::Filemanagement::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acmecorp.filemanagement.v1.data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.acmecorp.filemanagement.v1B\tDataProtoP\001\242\002\003AFX\252\002\032Acmecorp.Filemanagement.V1\312\002\032Acmecorp\\Filemanagement\\V1\342\002&Acmecorp\\Filemanagement\\V1\\GPBMetadata\352\002\034Acmecorp::Filemanagement::V1'
  _globals['_FILE']._serialized_start=69
  _globals['_FILE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
